version: '3'
networks:
  my-app-network:
    driver: bridge

services:
  fastapi_app:
    container_name: fastapi_app
    restart: always
    image: ghcr.io/capstone2024-student-counselling-ai-web/capstone_design-fastapi${BRANCH_NAME}
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - my-app-network
    volumes:
      - ./mlp_model.joblib:/app/AI/mlp_model.joblib

  react_app:
    container_name: react_app
    restart: always
    image: ghcr.io/capstone2024-student-counselling-ai-web/capstone_design-react${BRANCH_NAME}
    ports:
      - "3000:3000"
    networks:
      - my-app-network
    depends_on:
      - fastapi_app