version: '3'
networks:
  my-app-network:
    driver: bridge

services:
  flask_app:
    container_name: flask_app
    restart: always
    image: ghcr.io/capstone2024-student-counselling-ai-web/capstone_design-flask${BRANCH_NAME}
    ports:
      - "5000:5000"
    networks:
      - my-app-network

  express_app:
    container_name: express_app
    restart: always
    image: ghcr.io/capstone2024-student-counselling-ai-web/capstone_design-express${BRANCH_NAME}
    ports:
      - "3001:3001"
    networks:
      - my-app-network
    depends_on:
      - flask_app

  react_app:
    container_name: react_app
    restart: always
    image: ghcr.io/capstone2024-student-counselling-ai-web/capstone_design-react${BRANCH_NAME}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://express_app:3001
    networks:
      - my-app-network
    depends_on:
      - express_app

  nginx:
    container_name: proxy_nginx
    restart: always
    image: ghcr.io/capstone2024-student-counselling-ai-web/capstone_design-nginx${BRANCH_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - react_app
      - express_app