version: '3'
networks:
  my-app-network:
    driver: bridge

services:
  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./capstone_design/mysql_db/initdb:/docker-entrypoint-initdb.d
    networks:
      - my-app-network

  fastapi_app:
    container_name: fastapi_app
    restart: always
    build: ./capstone_design/fastapi_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - my-app-network
    depends_on:
      - mysql_db

  react_app:
    container_name: react_app
    restart: always
    build: ./capstone_design/react_app
    ports:
      - "3000:3000"
    networks:
      - my-app-network
    depends_on:
      - fastapi_app